### ISSUE TITLE
Errors when trying to mix basic and assembly code

### ISSUE THREAD

**Issue by johanberntsson** [neilsf/xc-basic3#100]
I'm trying to pass a basic variable (swp) to inline assembly code

    dim swp as byte
    function  nyswap as byte () static
        asm
            lda {self}.swp
            asl
            adc  #$80
            rol
            asl
            adc  #$80
            rol
            sta {self}.swp
        end asm
        return 0
    end function

I get these errors. Changing to sub instead of function doesn't make any difference

    ** ERROR ** There has been an error while trying to execute DASM, please see the bellow message.
    Tried to execute: ../../dasm/dasm /tmp/xcbtmp_33FD8568.asm -obin/demo.prg -s/tmp/xcbtmp_33FD8568.sym
    /tmp/xcbtmp_33FD8568.asm (2065): error: Not enough args passed to Macro.
    /tmp/xcbtmp_33FD8568.asm (2072): error: Not enough args passed to Macro.

    Unrecoverable error(s) in pass, aborting assembly!
    Complete. (5)

Is the syntax wrong, or is this a bug in the compiler?

**Comment by neilsf** [comment]
It's because the substitution of {self} is not (yet) implemented in version 3. I'll fix this.

**Comment by neilsf** [comment]
Btw, `{self}.swp` will only work for a passed argument or local variable, not on globals.

**Comment by johanberntsson** [comment]
ok, I'll change to a local variable and test again once self is implemented

**Comment by neilsf** [comment]
Okay, so since XC=BASIC3 handles variables differently, I came up with a different syntax:
The string {var_name} in inline assembly will be replaced with the label of that variable. The variable is searched per the XC=BASIC rules: local variables first, if not found, then global variables are searched.
Here is an example:
```
a = 2
b = 7
SUB test () STATIC
  DIM a AS BYTE ' Local variable
  a = 5
  ASM
    lda #$06
    sta {a}
    sta {b}
  END ASM
  PRINT a
END SUB

CALL test ()
PRINT a
PRINT b
```
