### ISSUE TITLE
CHARAT fails to compile if 2nd param is a literal

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#102]
![image](https://user-images.githubusercontent.com/14124210/152519202-2ae7fe26-215b-4ad4-bfa7-8e498445caac.png)

**Comment by neilsf** [comment]
It works for me. What is the error that you're getting exactly?

**Comment by neilsf** [comment]
Ahhh, okay, it's a whitespace issue. It fails to compile when there's whitespace after the number 5. I'll fix. Thanks
