### ISSUE TITLE
FOR loop with negative STEP does not evaluate

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#109]
```
FOR b AS BYTE = 5 TO 1 STEP -1
  PRINT b
NEXT b
```

**Comment by orlof** [comment]
Ah, I undestood that STEP is now byte -> cannot be negative.

**Comment by orlof** [comment]
Works perfectly with INT

**Comment by orlof** [comment]
It did not give any compiler error when trying to set -1 to byte.

**Comment by neilsf** [comment]
> It did not give any compiler error when trying to set -1 to byte.

It gave a warning that you were converting the number -1 (int) to byte. This for statement is perfectly valid but it never executes because 5 is already larger than 1. FOR loops on bytes can not go downwards.

**Comment by neilsf** [comment]
Any improvement tips are welcome though...

**Comment by orlof** [comment]
Is there a reason (well I suppose performance) for the requirement of STEP type being the same as looping variable type.
```
DIM b AS BYTE
b = CBYTE(100) + CINT(-1)
PRINT b
```
...is a valid code and produces 99.

**Comment by neilsf** [comment]
> Is there a reason (well I suppose performance) for the requirement of STEP type being the same as looping variable type.

Performance and overflow-safety.

In your example, overflow is allowed and therefore 100 + 255 = 99.

In a FOR loop, overflow can not be allowed because then loops would never stop. For example:

`FOR i AS BYTE = 250 TO 255 STEP 2`

It would not stop at the last iteration as 254 + 2 = 1, that is smaller than 255 so we're going around.

**Comment by orlof** [comment]
Hmmm... fair enough. Would it work if negative STEP sign were not handled as adding a negative value, but in separate code path that would subtract the positive value (the positive value still being enforced to be a BYTE)? Then overflows could still be handled and decreasing loops allowed even with unsigned types.
I don't know if I was able to explain myself 🤔
