### ISSUE TITLE
Latest compiler failing with bad path error. (Windows)

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#11]
Just downloaded the version built 22 hours ago. Now getting this:

![image](https://user-images.githubusercontent.com/14124210/145203938-4e6b08b0-de95-4762-b8ec-f28ee07c1643.png)

**Comment by neilsf** [comment]
Yeah, dir separator should be a backslash in Windows.
I've pushed a fix. Can you please download new version and try again? Thanks for reporting!

**Comment by neilsf** [comment]
Thanks for testing. I'm closing this issue.
