### ISSUE TITLE
Text screen garbage issue

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#123]
In my color picker program I am at times getting garbage on the screen. It works on startup and as you change colors works like 90% of the time. The other 10% I get garbage on the screen. I have tried to find a pattern but cannot.  Being that the same method is call to draw the screen with only the color vars changed I have no idea if its me or a bug. In the ZIP colorpicker.bas is the startup program. 
[colorPicker.zip](https://github.com/neilsf/xc-basic3/files/8059621/colorPicker.zip)
![image](https://user-images.githubusercontent.com/14124210/153839179-afa36a1d-ae66-4e05-9d5c-97a9726504ea.png)
![image](https://user-images.githubusercontent.com/14124210/153839701-4af35c92-ee87-452f-b5d0-309188836967.png)

**Comment by jakebullet70** [comment]
Ok, I will clean some stuff up. Question, can the stack be cleared programmatically? Or is there internal stuff I have no idea about?

**Comment by neilsf** [comment]
No, it is auto-emptied at the end of each string expression evaluation. Overflow should not happen normally, but there can be a bug in compiler or a bug in the program logic that causes this. Since the bug in your app seems quite random, I can't tell which :-(

**Comment by jakebullet70** [comment]
As a retired programmer with 35+ years experience...  "Since the bug in your app seems quite random"  I totally get it! LOL. I will see if I can nail it down to something that can be reproduced.

**Comment by jakebullet70** [comment]
OK, here is something reproducible! 
[20.zip](https://github.com/neilsf/xc-basic3/files/8067588/20.zip)
![image](https://user-images.githubusercontent.com/14124210/154031065-43ed7c95-90f5-478b-9194-cee2e3768289.png)
![image](https://user-images.githubusercontent.com/14124210/154031151-04cb12e5-9e6e-48c5-ae1d-7ee1bd02789a.png)
![image](https://user-images.githubusercontent.com/14124210/154031177-9c6579a6-66fe-4d29-9040-06ffa0da5c61.png)

**Comment by neilsf** [comment]
Excellent, thanks! I'll look into it.

**Comment by jakebullet70** [comment]
Even with me fixing that there is still some corruption all though its now like 1 in 50. I will keep testing.

**Comment by neilsf** [comment]
Of course. You have to initialize the variable, otherwise
1) its initial value will be random
2) you get an overflow during subsequent function calls (it grows by every call)
Variables are not automatically initialized in XC=BASIC.

**Comment by neilsf** [comment]
Btw, this version of your function (that you have commented out) is _much faster_, why don't you use that:
````
DIM tmp$ AS STRING * 96
POKE @tmp$, count
MEMSET @tmp$ + 1, count, character
RETURN tmp$
````
Another tip: Using the `;` character in a PRINT statement is faster and more efficient than concatenating string with the `+` operator, e. g `PRINT "hello "; name$` is faster than `PRINT "hello " + name$`.

**Comment by jakebullet70** [comment]
I would think though when initializing a string the default LEN should be 0 or  "".

**Comment by Thraka** [comment]
@neilsf @jakebullet70 this possibly be the source of the problem? Maybe even related? I didn't want to open another issue since this issue is dealing with screen corruption. This code causes the screen memory to get jumbled

```basic
FOR X AS BYTE = 0 TO 30
    PRINT X,X,X,X,X
NEXT X
```
![xc](https://user-images.githubusercontent.com/2672110/154362175-be005973-67bf-4d45-a304-5169343e30df.gif)

**Comment by neilsf** [comment]
@Thraka it looks like a different issue

**Comment by neilsf** [comment]
Opened #131

**Comment by jakebullet70** [comment]
@neilsf 
While garbage on the screen is SO much better in the latest version I ran into an issue I think that is with MID$.
Its in my Instr() function. It return the wrong value sometimes. 
If you look at the example it works 7 times but fails on the 8 by returning the wrong value. **At least it is reproducible.** 
Not so sure the is a screen garbage issue but if the wrong value is returned and I use it in a TEXTAT I can see memory garbage issues happening.

[20.zip](https://github.com/neilsf/xc-basic3/files/8095003/20.zip)

**Comment by jakebullet70** [comment]
Going to close this, while I am still at times seeing garbage on the screen (it is SO much better) I will post more accurate bugs to chase them down.
