### ISSUE TITLE
Issue with DATA statements and binary

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#124]
Trying to convert the V2 Tetris game to V3. Ran into this issue with the binary DATA statements.

![image](https://user-images.githubusercontent.com/14124210/153850766-420cb80f-0b42-40ac-984f-bd6fabacd9e8.png)
[tetris.zip](https://github.com/neilsf/xc-basic3/files/8060061/tetris.zip)

**Comment by neilsf** [comment]
Binary numbers are always evaluated unsigned. The second number in line 50 is beyond 32767 when interpreted as unsigned. The correct data type for these numbers is WORD, not INT.

**Comment by neilsf** [comment]
.... as an improvement, I'll see if the compiler can allow signed numbers as binary.

**Comment by neilsf** [comment]
.... no it cannot. Just like everything in XC=BASIC, numers are evaluated without knowing their purpose, so the compiler must take assumption on their types. If a number is binary or hex, unsigned type is assumed.
