### ISSUE TITLE
Require whitespace after command name

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#125]
If you have a function named `PrintDirectory` and then try to call it, the compiler errors with `Variable Directory doesn't exist` because it resolved `Print` out of the name first when there is an error on that line.

For example if you have the following code:

```basic
SUB PrintTest() STATIC SHARED

    PRINT "TEST"

END SUB

PrintTest()
```

Which is an error because it requires `CALL` to be used, the error printed is:

```
test.bas:7.0: ERROR: Variable "Test" does not exist or is unknown in this scope
```

If you rename the SUB to something else, like `PTest` and update the bad calling code with the same name, the error now changes to:

```
test.bas:7.0: ERROR: Syntax error
```

**Comment by neilsf** [comment]
The only bug I can see here is that `PrintTest()` should not be interpreted as `PRINT Test()` without the space. Writing the name of a SUB without the `CALL` keyword is indeed a syntax error.

**Comment by Thraka** [comment]
Correct. This is how I discovered the problem. I forgot `CALL` but the error wasn't making sense since it was trying to report a probem with the whitespace and `PRINT`
