### ISSUE TITLE
Converting V2 Tetris code - Wait command seems to have an issue.

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#129]
Working on converting the V2 Tetris over to V3 and ran into this issue.
As I understand this should pause about 4 seconds (PAL) but pauses like  10ms
I am using VICE set to a PAL machine

CONST VICII_RASTER = $d012

FOR ii as byte = 0 to 200  
	WAIT VICII_RASTER, 255
	'print str$(PEEK(VICII_RASTER)) ; "  " 
NEXT

Am I missing something stupid?

**Comment by orlof** [comment]
I think your wait only waits until $d012 has non-zero value. You specify bit pattern 255 which is ANDed with $d012 and only if result is zero then wait continues.
Wait command always makes my brain hurt, but I don't think that you can use it to wait for a specific value. I would do something like:
```
CONST VICII_RASTER = $d012

FOR ii as byte = 0 to 100
WAIT VICII_RASTER, 128
WAIT VICII_RASTER, 128, 128
'print str$(PEEK(VICII_RASTER)) ; " "
NEXT
```

**Comment by neilsf** [comment]
Correct. In v2 there was WATCH to wait for a specific value but it is not really needled as it does the same as
`DO : LOOP UNTIL PEEK(VICII_RASTER) = 255`
