### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#13]
Please submit this bug to https://github.com/neilsf/xc-basic3/issues
> exit status: 1
> cd C:\xcbasic3
> C:\xcbasic3\bin\Windows\xcbasic3.exe "6.bas" "6.prg"
6.bas:39.0: WARNING: Downcasting from int to byte truncates value
** ERROR ** There has been an error while trying to execute DASM, please see the bellow message.
Tried to execute: "dasm.exe" "C:\Users\jakeb\AppData\Local\Temp\xcbtmp_F9CFF990.asm" -o"6.prg
[6.zip](https://github.com/neilsf/xc-basic3/files/7718761/6.zip)
"

**Comment by neilsf** [comment]
Thanks for reporting, @jakebullet70.
It's because a missing END IF somewhere around line 41.
However the compiler should throw an error and not pass the erroneous code to DASM. I'll fix it.

**Comment by neilsf** [comment]
Fixed.
