### ISSUE TITLE
PRINT with numbers isn't as robust as BASIC v2

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#130]
When a numeric value is printed in BASIC v2, it contains spaces around it to make it print prettier. This doesn't happen in XC-BASIC. This makes it hard to make nice looking text with numbers as it requires you to put `" "` between items.

**Comment by neilsf** [comment]
On purpose. See, in CBM BASIC you have no option to exclude the leading space from numbers, while in XC=BASIC you have the option to include it, like `PRINT " "; x`
