### ISSUE TITLE
PRINT # behaves different from PRINT

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#134]
In trying to debug why some disk routines of mine aren't working. I was trying to see if it was something going into the PRINT# statement to the disk drive. I discovered this:

It seems `,` is being printed when you use it in PRINT#

```basic
DIM dirTrack AS BYTE: dirTrack = 18
DIM dirSector AS BYTE: dirSector = 1

OPEN 3, 3
PRINT #3, "u1 2 0 " , STR$(dirTrack) + " " + STR$(dirSector)
PRINT "u1 2 0 " , STR$(dirTrack) + " " + STR$(dirSector)
CLOSE 3
```
produces the following output:
```
u1 2 0 ,18 1
u1 2 0    18 1
```

**Comment by neilsf** [comment]
CBM BASIC:
When printing on the screen, `,` will cause to move the cursor to the next tab position. When writing to disk, `,` will pad the record with spaces.

XC=BASIC:
When printing on the screen, `,` will cause to move the cursor to the next tab position. When writing to disk, `,` will output a comma character.

Is it really required to pad with spaces? Would it be okay to add a single space?

```
u1 2 0    18 1
u1 2 0 18 1
```

Are the above equivalent?

**Comment by Thraka** [comment]
@neilsf Sorry, that was my misconception as I didn't expect the , to be there. I'm not **really** trying to space them out in anyway except to just add nice spaces between items without having to concatenate strings.

In CBM you can more easily get a blank space between things, so that they look nice.

My question really is how do I do that here? So I can avoid operations like `STR$(dirTrack) + " " + STR$(dirSector)` when printing dynamic content to the screen or a file number?

**Comment by neilsf** [comment]
Why don't you use semicolons. I think the drive expects one space between the numbers (I'm not sure, I don't really know the 1541 DOS).

```
PRINT #3, "u1 2 0 "; STR$(dirTrack); " "; STR$(dirSector)
```

**Comment by Thraka** [comment]
I don't know why my brain didn't think of that... I guess I was too focused on "what is being automatically placed between variables"
