### ISSUE TITLE
Error handler not working.

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#136]
Error handler not working.
Sample is from the docs.

~~~
DIM filename$ AS STRING * 16
ON ERROR GOTO errhandler
try:
  INPUT "enter filename: "; filename$
  OPEN 2, 8, 2, filename$
  ' code that reads file...
  CLOSE 2
END  
errhandler:
  CLOSE 2
  IF ERR() = 4 THEN
    PRINT "file not found, try again"
    GOTO try
  END IF
  PRINT "other error, exiting"
end
~~~

**Comment by neilsf** [comment]
The example is wrong and it was written when I used an earlier aproach to the OPEN command. OPEN will not throw an error any more, but you have to read the disk error channel to get a status. I'll rewrite the example.
