### ISSUE TITLE
Using a string with INPUT# seems to change the string length, expected?

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#138]
I'm trying to make my disk reading routines performant. A file name in the directory of a disk is 16 characters long. When I use `INPUT#` to read the string, it seems to change the string variable to be around 50 characters big.

```basic
DIM device as BYTE: device = 8
DIM fileName AS STRING * 16
DIM fileTrack AS BYTE
DIM fileSector AS BYTE
DIM fileType AS BYTE
DIM discard as BYTE

OPEN 15, device, 15
OPEN 2, device, 2, "#"

REM read track 18 sector 1 into disk drive ram
PRINT #15, "u1 2 0 18 1"

REM read the first two bytes out of disk memory (pointer to next track/sector)
READ #2, discard, discard

REM read the directory entries
FOR counter AS BYTE = 0 to 7

    REM read first 3 bytes of dir entry
    READ #2, fileType, fileTrack, fileSector

    REM no entry here -- move on
    IF fileType = 0 AND fileTrack = 0 AND fileSector = 0 THEN CONTINUE FOR

    INPUT #2, fileName

    PRINT "-";fileName;"-"

NEXT counter
```

**Comment by neilsf** [comment]
The device returns `A0` bytes after the file name while STATUS is zero (=no error). Is `A0` a valid terminator? I don't think so but I'll try to look it up in the 1541 manual.

**Comment by Thraka** [comment]
@neilsf For the disk name and file name, it's always 16 bytes padded with `A0`. It's used to fill in the rest of the name if the name is shorter than 16 bytes.

This is really just an artifact of me trying to figure out how to use the language to get a specific amount of characters from the logical file. I thought perhaps the code would for terminate the input based on the size of the string, versus creating a new string.

I think I can close this since this is the expected behavior.

**Comment by neilsf** [comment]
Okay, if it's a padded string, you can't use `INPUT#` to read it as a whole, but you can use `GET#` to get it char by char.
