### ISSUE TITLE
Add support for using byte arrays in READ#/GET#

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#139]
Each time READ#/GET# is called, there is prep that the compiler does, such as calling `KERNAL_CHKIN`, reading the byte, then calling `KERNAL_CLRCHN`. You can pass multiple variables to these methods, storing each byte into the relative variable.

However, this is limiting because lets say I wanted to load an entire disk block (256 bytes), I would have to call READ# 256 times, at each index of the array. This is a lot of overhead.

It would be nice to pass in an array and have the code internally loop over the memory, storing each byte from `I_BINREAD` into the array.

**Comment by neilsf** [comment]
I'm okay with the idea. If one of the parameters of `READ#` is an array and no subscript is specified, the whole array should be read into.

```
READ #8, myarr(0) ' reads single value
READ #8, myarr ' reads an array of values
```

**Comment by jakebullet70** [comment]
@Thraka  For our project can we toss in some inline ASM to get around this for the moment?

**Comment by Thraka** [comment]
Yeah we should be able to.

**Comment by Thraka** [comment]
@neilsf perhaps we should also add in string support too? INPUT# could replace the string length with what the input is reading, while READ# would respect the existing string size.

**Comment by neilsf** [comment]
> 

I'm not sure what you mean, sorry.

> @neilsf perhaps we should also add in string support too? INPUT# could replace the string length with what the input is reading, while READ# would respect the existing string size.

I'm not sure what you mean, sorry.

**Comment by Thraka** [comment]
Currently when you:

```basic
DIM value AS STRING * 10
```
You have a string that is 10 in size, right? When you use `INPUT #2, value` the size of the string is changed to whatever the `INPUT` command says you should have. Which is good because your reading records or something and you want the whole record string returned.

My idea is that `READ #2, value` would only read as many characters as can fit the string, 10. This is similar to how using the array would work.

But the problem is that READ just returns binary data and not the petscii like input does...

**Comment by neilsf** [comment]
`DIM value AS STRING * 10`

10 is the _maximum length_ of the string, not the actual length.

>  When you use INPUT #2, value the size of the string is changed to whatever the INPUT command says you should have.

If the number of bytes on disk exceeds 10, INPUT# should stop and not extend the string (which is NOT possible anyway because it corrupts memory after the string). So if this happens, that is a bug. I'll check that.

> My idea is that READ #2, value would only read as many characters as can fit the string, 10

`INPUT` _should_ behave like that :-)

**Comment by Thraka** [comment]
Ok then I think that the `INPUT #` is a bug 😁 because that's what I was experiencing. However, how does it know the max length of the string versus the actual? Is that info kept in a lookup table?

**Comment by neilsf** [comment]
> However, how does it know the max length of the string versus the actual?

It is known in compile time. This is why you must use `DIM` to specify max length.

**Comment by neilsf** [comment]
Closing this because the requested feature can be worked out in user code.
