### ISSUE TITLE
Compile error - Input# statement

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#14]
Please submit this bug to https://github.com/neilsf/xc-basic3/issues
> exit status: 1
> cd C:\xcbasic3
> C:\xcbasic3\bin\Windows\xcbasic3.exe "6.bas" "6.prg"
6.bas:68.0: WARNING: Downcasting from int to byte truncates value
** ERROR ** There has been an error while trying to execute DASM, please see the bellow message.
Tried to execute: "dasm.exe" "C:\Users\jakeb\AppData\Local\Temp\xcbtmp_7C5995A0.asm" -o"6.prg
[6.zip](https://github.com/neilsf/xc-basic3/files/7720556/6.zip)
"

**Comment by neilsf** [comment]
Fixed. Thanks for reporting.
