### ISSUE TITLE
EXIT DO in DO loop in FOR loop causes compilation error

### ISSUE THREAD

**Issue by fredrikr** [neilsf/xc-basic3#141]
This program causes this error in line 9: Unclosed FOR block before LOOP.

If I comment out the IF ... EXIT DO line it works.

```
DIM j AS BYTE
DIM x AS BYTE

FOR j = 1 TO 2
	x = 3
	DO WHILE x > 1
		IF x < 2 THEN EXIT DO
		x = x - 1
	LOOP
NEXT j
```

**Comment by neilsf** [comment]
It works for me using the latest build (Linux). What is your build?

**Comment by fredrikr** [comment]
I have Windows. I have pulled the latest updates.

**Comment by neilsf** [comment]
Ok, I'll try to debug this on Windows. Thanks.

**Comment by jakebullet70** [comment]
Just cut and pasted this. compiles for me.

**Comment by jakebullet70** [comment]
![image](https://user-images.githubusercontent.com/14124210/154955093-596482ca-f948-41d9-92d4-b67bb9a81e78.png)

**Comment by fredrikr** [comment]
My repo includes commit 244e321. I use tab for indentation and CR+LF at the end of each line. This is what I get when I compile:

```
C:\XC-BASIC3\bin\Windows\xcbasic3.exe exitbug.bas
** NOTE ** Output not specified, defaulting to exitbug.prg
exitbug.bas:9.0: ERROR: Unclosed FOR block before LOOP
```
![image](https://user-images.githubusercontent.com/1001548/154956353-764aac84-f5ff-4b06-9c32-eec538b2c90b.png)

**Comment by jakebullet70** [comment]
If i paste in Notepad++ i can see the TAB chars. When you download the latest version are you overwriting everything?  I had an issue when i was just over writing the compiler.

![image](https://user-images.githubusercontent.com/14124210/154957302-ae249989-7887-4e7f-9287-053b57b5057d.png)

**Comment by neilsf** [comment]
Tabs and line endings doesn't matter in this case. This is a bug that was fixed weeks ago.

**Comment by fredrikr** [comment]
I haven't tried XC=BASIC 3 until yesterday, when I cloned the repo and started experimenting with it. So I'm using the latest build and nothing has been overwritten.

**Comment by fredrikr** [comment]
The compiler:

```
 Directory of C:\XC-BASIC3\bin\Windows

2022-02-20  19:29         8 192 512 xcbasic3.exe
               1 File(s)      8 192 512 bytes
```

**Comment by neilsf** [comment]
No worries, I'll try it on a Windows machine.

**Comment by fredrikr** [comment]
Looks like I had the develop branch instead of the main branch.

I just picked the default branch when cloning with SourceTree.

Got main branch now and it's working.
