### ISSUE TITLE
INPUT # isn't respecting STRING max length

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#146]
`INPUT #` isn't pulling in just the characters to fill the string from the data channel. Here is some code that should pull in just the length of the directory entry, 16 bytes:

```basic
REM Open command channel 15 followed by data channel 2
OPEN 15, 8, 15
OPEN 2, 8, 2, "#"

DIM dead AS BYTE

DIM fileName AS STRING * 16
DIM fileTrack AS BYTE
DIM fileSector AS BYTE
DIM fileType AS BYTE

PRINT #15, "u1 2 0 18 1"
PRINT #15, "b-p 2 0"

REM read the next track/sector for directory
READ #2, dead, dead

REM cycle files in block
FOR counter AS BYTE = 0 to 7

    fileName = ""
    READ #2, fileType, fileTrack, fileSector

    INPUT #2, fileName
    REM comment out the above line and restore the following FOR loop to see the difference of getting it byte-by-byte
    REM FOR counterb AS BYTE = 0 TO 15
    REM   GET #2, dead
    REM    fileName = fileName + CHR$(dead)
    REM NEXT

    PRINT fileType;" ";fileTrack;" ";fileSector;" -";fileName;"- len="; LEN(fileName)

    REM reletive file track/sector/length
    READ #2, dead, dead, dead
    REM nothing
    READ #2, dead, dead, dead, dead
    REM new file track/sector if overwritten with @: 
    READ #2, dead, dead
    REM block count, low/high
    READ #2, dead, dead
    REM two empty bytes
    READ #2, dead, dead
NEXT counter

CLOSE 2
CLOSE 15
```

**Comment by neilsf** [comment]
So the current implementation is as follows:

1. The `INPUT#` command first reads the string into the buffer. The buffer is 96 chars long. All characters are consumed until a comma ($2C) or end-of-line ($0D) character is encountered.
2. Then the buffer is copied to the variable but only as many chars as the variable can hold (that is, the max length of the string).

Therefore I don't think it's a bug, but `INPUT#` is not the right command for this purpose. I think you can't do the above using `INPUT#` in CBM BASIC, either, you have to get the string char by char using `GET#`.

Let me know if you think I'm wrong.

**Comment by Thraka** [comment]
@neilsf I may have created this issue because of your comment here that indicated it should stop at the maximum length of the string: https://github.com/neilsf/xc-basic3/issues/139#issuecomment-1048131657

I'm fine with whichever way it should operate, perhaps in the linked issue there can be something else, a different command or perhaps add string support to READ that would work with passing a string and only filling the max size.
