### ISSUE TITLE
'Function XXXXX declared but not defined' warning showing wrong source module

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#156]
Also is there a final BAS module with all 'included' code we can review?

![image](https://user-images.githubusercontent.com/14124210/156568227-dd8a2c04-7b99-4649-a8e0-98aa49c44afb.png)

**Comment by neilsf** [comment]
> Also is there a final BAS module with all 'included' code we can review?

No, they're not merged but compiled one after another.
