### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#16]
re-factoring some C64 Dir code.

Please submit this bug to https://github.com/neilsf/xc-basic3/issues
> exit status: 1
> cd C:\xcbasic3
> C:\xcbasic3\bin\Windows\xcbasic3.exe "disk.bas" "disk.prg"
disk.bas:20.0: WARNING: Downcasting from int to byte truncates value
disk.bas:49.0: WARNING: Downcasting from int to byte truncates value
** ERROR ** There has been an error while trying to execute DASM, please see the bellow message.
Tried to execute: "dasm.exe" "C:\Users\jakeb\AppData\Local\Temp\xcbtmp_9C2A7B4B.asm" -o"disk.prg"

[disk.zip](https://github.com/neilsf/xc-basic3/files/7740717/disk.zip)

Please submit this bug to https://github.com/neilsf/xc-basic3/issues
> exit status: 1

**Comment by neilsf** [comment]
It looks like PRINT# and INPUT# are not working yet quite well. I'll fix.

**Comment by neilsf** [comment]
Fixed. INPUT# and PRINT# now working. I'll update the docs as there are a few minor differences from CBM BASIC.

**Comment by jakebullet70** [comment]
I will get some testing in today.

**Comment by jakebullet70** [comment]
Closing, seems to be working fine now.
