### ISSUE TITLE
TEXTAT color parameter currently has no effect

### ISSUE THREAD

**Issue by locodarwin** [neilsf/xc-basic3#164]
When using the TEXTAT command in xcb3, the color parameter currently has no effect. Documentation for TEXTAT indicates color is a parameter, so either the feature is missing/nonfunctional or the docs will need to be updated. I am happy to change the documentation if the omission is intentional.

Sample:

```
textat 0, 0, "hello, world", 7
textat 0, 1, "hello, world", 6
textat 0, 2, "hello, world", 5
```
This will print 3 lines of text at the top of the screen but will not set the colors. The text retains whatever color codes were in color memory at those locations.

Tested on targets c64, cplus4
Repo (pull) current as of 03/20/22
xcb3 compiled in a Windows x64 environment

**Comment by neilsf** [comment]
Fixed in v3.0.2
