### ISSUE TITLE
Feature request: C128 as compile target

### ISSUE THREAD

**Issue by locodarwin** [neilsf/xc-basic3#166]
This really shouldn't be as bad as it sounds. The C128 in native mode actually has more in common with the C64 than the C16/plus4 machines in terms of memory layout, register use, routines, etc. It would be too much to expect XC=BASIC itself to do bank switching and other MMU memory configurations in the runtime. I don't think it's worth the bother. A simple default MMU configuration with BASIC ROMs switched out would still leave enough room for XC=BASIC programs, especially since the programmer can use tricks outside of XC=BASIC to get access to that extra memory. The basic idea:

1. Leave the default start of BASIC for 128 mode as is ($1c01). No MEMTOP woes to worry about, of course.
2. BASIC loader stub loads and runs as usual, but after the STUB and before user code, the MMU is configured to switch out the BASIC 7.0 ROMs (32k total!) but keep the KERNAL, I/O, screen editor, and register areas - this is all handled by flipping bits in one single register (MMUCR which is $ff00 and visible in any bank config). Basically setting $ff00 to %00001110 establishes the necessary ROM pattern. All other mem configuration (i.e. identifying and sizing the common RAM sections) is fine at default.
3. XC=BASIC changes nothing about its own memory use, except heeding the ROM, IO, and editor space that starts at $C000 in BANK0. XC=BASIC does everything in BANK0 as if that second set of 64k RAM doesn't exist. No mucking about with the MMU or trying to get variable data in and out of BANK1. With BASIC switched out that leaves ~42k left for XC=BASIC in BANK0. Plenty.
4. If the programmer wants to access BANK1, there are built in helper utilities in common RAM (below $03ff) that can do things like LDA/LDX/LDY across banks, JSRFAR and JMPFAR for running code in any bank not currently switched in, etc. The Kernal handles the switching behind the scenes. This could all be orchestrated with an extension written in ASM similar to my REU extension. In fact, BANK1 would be treated much like REU memory.
5. That's really it. Sprites, SID, VIC-II, interrupts, timers....these are all handled the same way as the C64, Same registers, same values, same methods for doing things. Kernal routines are all exactly the same, too, although the 128 does add a few more.

Extensions can (will) be written to do the following:

- Provide runtime access to BANK1 RAM through memory move/shift/copy (bonus: if there's an REU installed the memory movement will be lightning fast)
- Operate the VDC (so much potential there - 80 columns, two sets of characters in use at the same time, extra memory to use, tons more)
- Configure the MMU on the fly for shifting memory around very quickly - useful for switching code modules or data in and out
- Burst mode on the 1571/1581 and some other non-1541 IEC drives.

Of course at the end of the day it would be ideal for XC=BASIC to utilize the MMU for BANK1 variable and data storage, as that would more than double the amount of memory directly available for single programs, but the amount of refactoring it would take to make the MMU do this would require extensive rework. The solution outlined above seems a nice compromise that would still allow 128 owners to take advantage of XC=BASIC.

End result memory map shown here. The BASIC 7.0 ROMs ordinarily map to $4000 to $BFFF and BASIC does all the MMU work to get to that RAM underneath. With those ROMs switched out for all of runtime it would look like this:

![128 mem map](https://user-images.githubusercontent.com/12356723/159222502-ca729ac0-4d89-4998-a160-0e1acf346073.png)

**Comment by neilsf** [comment]
Hi @locodarwin 

Thanks for the detailed info. If that's really it, I can do the simple things (start address, MMU configuration at beginning and restoring configuration at end).

> Extensions can (will) be written to do the following

It would be awesome to have these features but I won't be able to implement them. Can you write such an extension? If the compiler has to be modified (e. g adding new keywords or modifying existing ones), let me know.

> Of course at the end of the day it would be ideal for XC=BASIC to utilize the MMU for BANK1 variable and data storage, as that would more than double the amount of memory directly available for single programs

I'm more concerned about speed. If the runtime has to switch banks before and after every variable access, that'll make things much slower.

>  The solution outlined above seems a nice compromise that would still allow 128 owners to take advantage of XC=BASIC.

Agreed.

**Comment by locodarwin** [comment]
I will be happy to do the extensions. Thank you for considering this!

You don't even need to configure the MMU on exit. Once an ML program exits, the Kernal handles switching the BASIC ROMs back in automatically to BASIC's "BANK15" configuration.

**Comment by neilsf** [comment]
>  Once an ML program exits, the Kernal handles switching the BASIC ROMs back in automatically to BASIC's "BANK15" configuration.

On exit, XC=BASIC jumps to the cold start address of BASIC (on the C64 it is `jmp ($A002)`) so I guess BASIC ROM must be banked in before.

**Comment by locodarwin** [comment]
Oh, you're not just doing a final RTS and letting the Kernal deal with returning to BASIC? On the C128 that generally works.

**Comment by neilsf** [comment]
> Oh, you're not just doing a final RTS and letting the Kernal deal with returning to BASIC?

No, because the ZP area used by BASIC is messed up by the XC=BASIC runtime, BASIC needs a clean start.

**Comment by neilsf** [comment]
Hi @locodarwin 
I'm currently implementing C128 support but I'm kind of stuck. Are you available to assist? I'd PM you.
Thanks.

**Comment by locodarwin** [comment]
Whoops, sorry I missed this! Yes, I will assist if I'm able.

**Comment by neilsf** [comment]
This has been completed, waiting for release.
