### ISSUE TITLE
Inline ASM produces compile errors when using labels

### ISSUE THREAD

**Issue by locodarwin** [neilsf/xc-basic3#167]
Using the ASM keyword breaks during compile if labels are used in the ASM code. Consider the following nonsense (but DASM legal) code:

```
asm
.start
	lda #$00
	sta $c000
	bne .start
.end
end asm
```

The compiler errors out with the following messages:

![Image 123](https://user-images.githubusercontent.com/12356723/159340055-9bf8ca15-898b-400b-93ea-8e40516d64c5.png)

The above labels are legal DASM local labels (e.g. no whitespace at beginning of line) and work as written in XCB v2.x. I also tried global labels that end in ":" and even dynamic labels. All produce the same issue. If I remove the labels and the branch, it compiles fine.

While the code does nothing useful, it should still compile. Shouldn't it?

**Comment by locodarwin** [comment]
Update: same issue with the ASM portions when I try to compile Oliver's mazegen v3 code that was posted on the XC=BASIC facebook wall.

**Comment by neilsf** [comment]
Your example works for me. Are you sure you're using the latest version?

**Comment by locodarwin** [comment]
I'll check my environment as we discussed in the Discord. This is probably a no-bug.

**Comment by locodarwin** [comment]
Found the problem. I'm in a Windows environment and using Windows version of the text editor Notepad++. If I use nano at the command line instead I get a file that DASM seems to like better. DASM is the pickiest damned compiler I've ever worked with when it comes to formatting. Sheesh.
