### ISSUE TITLE
Returning string from FUNCTION stripping off last char

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#169]
Trying to return 3 char's but only returning 2
if i set 'AS STRING * 4' it works.

``
FUNCTION GetFileType AS STRING * 3 (fileTypeByte AS BYTE) STATIC
	CONST FILE_TYPE_PRG = 130
    CONST FILE_TYPE_SEQ = 129
    CONST FILE_TYPE_USR = 131

	IF fileTypeByte = FILE_TYPE_PRG  THEN RETURN "prg"
	IF fileTypeByte = FILE_TYPE_SEQ THEN RETURN "seq"
	IF fileTypeByte = FILE_TYPE_USR THEN RETURN "usr"
	
	RETURN STR$(fileTypeByte)
END FUNCTION

PRINT "{clr}"
PRINT GetFileType(129)
END
``

![image](https://user-images.githubusercontent.com/14124210/160115050-7bc9d4ca-2f89-4d29-9762-6c7c588b12db.png)

**Comment by neilsf** [comment]
Fixed in v3.0.3
