### ISSUE TITLE
Return string from a function seems to be corrupted

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#17]
![image](https://user-images.githubusercontent.com/14124210/147384265-cc44fbca-9ea5-4786-a840-d34c9da4d003.png)

[disk.zip](https://github.com/neilsf/xc-basic3/files/7775786/disk.zip)

**Comment by neilsf** [comment]
Fixed. Thanks for reporting!

**Comment by neilsf** [comment]
Fixed. Thanks for reporting!
