### ISSUE TITLE
Passing an blank string to a method is corrupting local vars

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#173]
`
declare SUB test() static
declare SUB test1(dd as string * 30) static

PRINT "{CLR}"
dim ff as byte
ff = 10
call test() : PRINT ff
call test() : PRINT ff
call test() : PRINT ff
call test1("hh") : PRINT ff
'call test1("") : PRINT ff
call test() : PRINT ff
end

SUB test() static
	ff = ff + 1
end sub

SUB test1(dd as string * 30) static
	ff = ff + 1
end sub`

![image](https://user-images.githubusercontent.com/14124210/160281106-43a80a22-9391-427c-9180-95db2fab79eb.png)

![image](https://user-images.githubusercontent.com/14124210/160281116-04d1e3ba-b9a5-4347-ade4-ad141e5c808e.png)

![image](https://user-images.githubusercontent.com/14124210/160281123-6ec43c60-e3de-470f-a3c5-f66256187da0.png)

 You see a reset to 0 here, I have also seen the var reset to 255

**Comment by neilsf** [comment]
Same as #172
