### ISSUE TITLE
allow multiple {variables} per line for inline ASM 

### ISSUE THREAD

**Issue by Jest0r** [neilsf/xc-basic3#178]
When using macros in an ASM block, it would be useful to be able to use more than one {variable} per ASM line.

from my testing:
```
target = $20
myconst = $43
ASM
;        asm_macro {target}, {myconst}  ; Does not work
        asm_macro {target}, #$43      ; works
END ASM
```

**Comment by Jest0r** [comment]
Not sure if that's a DASM limitation. If it is, I think we can close this

**Comment by neilsf** [comment]
> Not sure if that's a DASM limitation. If it is, I think we can close this

No it isn't. XC=BASIC replaces these {placeholders} but it only replaces one per line currently. It's just that I haven't had time for this for a while :-(
