### ISSUE TITLE
printing right$ can cause an infinite loop

### ISSUE THREAD

**Issue by mrg-75** [neilsf/xc-basic3#18]
The following code should print the word right

dim test$ as string * 10
test$ = "left right"
print right$(test$, 5)

but causes an infinite loop
![Capture](https://user-images.githubusercontent.com/61950078/147411225-a1d2e4b0-8e8d-4c07-814c-1656761ae5d4.PNG)

**Comment by neilsf** [comment]
Fixed, thanks for reporting! Pls note that to have the fix, you'll need to reinstall all files from the new version, not only the executable.
