### ISSUE TITLE
MOD doesn't work on some combinations of byte or word variables

### ISSUE THREAD

**Issue by JJFlash-IT** [neilsf/xc-basic3#182]
XC-Basic v3.0.6 (May 25 2022)

```
dim dividend as word
dim divisor as word

dividend = 70
divisor = 6

print dividend mod divisor
```
This prints 0.

```
dim dividend as byte
dim divisor as word
```
This prints 0 as well.

```
dim dividend as word
dim divisor as byte
```
This correctly prints 4.

Other combinations including `INT` seem to work fine.

**Comment by neilsf** [comment]
Looks like a bug in dividing WORD types, thanks for reporting.
