### ISSUE TITLE
User defined types don't work in ASM block's curly braces syntax

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#192]
```
TYPE sid
    init AS WORD
END TYPE

DIM music AS sid
music.init = $beef

ASM
    lda {sid.init}
END ASM
```
/var/folders/t8/ngfvr40134l01825gycspzg80000gn/T//xcbtmp_4DDE1127.asm (26): error: Not enough args passed to Macro.
/var/folders/t8/ngfvr40134l01825gycspzg80000gn/T//xcbtmp_4DDE1127.asm (27): error: Illegal character '{sid.init}'.
/var/folders/t8/ngfvr40134l01825gycspzg80000gn/T//xcbtmp_4DDE1127.asm (27): error: Illegal character '}'.

Fatal assembly error: Source is not resolvable.

**Comment by neilsf** [comment]
The variable name extrapolation in assembly blocks is currently limited to variables. UDT fields cannot be accessed this way.

**Comment by orlof** [comment]
Warning in ASM documentation would be nice as this was not quickly understood from the dasm error.
