### ISSUE TITLE
Cannot combine SHARED and @ in DIM

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#194]
```
DIM a AS BYTE SHARED @_a
_a:
DATA AS BYTE 0
```
lib_vic2.bas:1.21: syntax error near '@_a' in file lib_vic2.bas in line 1

FAST doesn't work either, but that wouldn't make any sense anyway.

**Comment by neilsf** [comment]
This is a mistake in the docs.
Try `DIM a AS BYTE @_a SHARED` or `DIM SHARED a AS BYTE @_a`, both should work.

**Comment by orlof** [comment]
It works!
