### ISSUE TITLE
[alpha 3.1 build] parser doesn't like apostrophe comment after command 

### ISSUE THREAD

**Issue by locodarwin** [neilsf/xc-basic3#195]
Applies to release/v3.1 only:

Comments after a command using the apostrophe (e.g. "border 0 ' change border color") fail to compile - the parser doesn't like it. This is a change in behavior. If we add a colon after the command ("border 0 : ' change border color") it works.

Test with:

```
border 0 : ' the parser won't complain here
background 0 ' but will complain here
```

**Comment by neilsf** [comment]
Resolved in latest v3.1 build.
