### ISSUE TITLE
[alpha 3.1 build] INPUT command adds CR to collected string

### ISSUE THREAD

**Issue by locodarwin** [neilsf/xc-basic3#196]
It seems the INPUT command adds the trailing CR to the collected string. The following code should work and print "you chose exit" if the user types "exit" and presses the RETURN key to complete the input:

```
dim a$ as string * 40
prompt:
input "type something: "; a$
print a$
if a$ = "exit" then
	print "you chose exit"
end if
goto prompt
```

Instead, the following code works, indicating that the CR from the input was added to the string at its last byte position. Note the inclusion of chr$(13) in the check:

```
dim a$ as string * 40
prompt:
input "type something: "; a$
print a$
if a$ = "exit" + chr$(13) then
	print "you chose exit"
end if
goto prompt
```

**Comment by neilsf** [comment]
Fixed in release/v3.1
