### ISSUE TITLE
[alpha 3.1 build] LOAD & INTERRUPTS don't mix?

### ISSUE THREAD

**Issue by Diduz** [neilsf/xc-basic3#198]
I'm having problems at loading binary files (through "LOAD") in a program where I'm using RASTER INTERRUPT.
I know I'm supposed to turn RASTER INTERRUPT OFF before loading files, but the program crashes to a simple "READY" screen even **_before_** I turn RASTER INTERRUPT ON!
I mean, the mere presence of the new interrupt routines in my code seems to prevent me from loading an external binary file, even when raster interrupts are still inactive.
If I remove any reference to the new alpha 3.1 INTERRUPTS commands, "LOAD" works as intended.
Before I try and understand if there's something wrong in my code (I'm still a newbie), I'd like to know if this is a bug in the alpha build. ;-)

**Comment by neilsf** [comment]
Well it is possible that the LOAD routine breaks if interrupts are used _even if they're turned off_. If the compiler encounters any interrupt commands, it redirects the IRQ vector ($0314) to XC=BASIC's custom routine _on program start_.

It might happen that LOAD conflicts with the custom IRQ routine. I'll have to try it myself to understand this better.

What platform is this? Are you trying to load from tape or disk?

**Comment by Diduz** [comment]
> What platform is this? Are you trying to load from tape or disk?

C64. Disk.
Thanks!

**Comment by neilsf** [comment]
Fixed. Thanks for the report.

**Comment by Diduz** [comment]
> Fixed. Thanks for the report.

You're welcome. :-) Thanks to you!
