### ISSUE TITLE
Optimise redundant pha-pla cycles

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#199]
I was debugging some code compiled with XCBasic and it seems that my coding style (use of SUB routines) generates some code that looks like redundant. Here is example:

```
SUB f(a AS BYTE, b AS BYTE) STATIC
    POKE 1024,a
    POKE 1025,b
END SUB

CALL f(24, 3)
```

Compiles to this:

```
    LDA #$FF    ; standard initialization code
    STA $15
    LDA #$00
    STA $0F
    LDA #$CF
    STA $10

    LDA $01     ; disable basic
    AND #$FE    ; optimize with "DEC $01"
    STA $01

                ; program code starts here
    LDA #$18    ; assign "a"
    PHA         ; -> optimize
    PLA         ; -> optimize
    STA $084B

    LDA #$03    ; assign "b"
    PHA         ; -> optimize
    PLA         ; -> optimize
    STA $084C

    JSR $0839   ; call "f"

    LDA $01     ; restore basic
    ORA #$01    ; optimize with "INC $01"
    STA $01

    JMP ($A002) ; THE END

                ; subroutine "f" starts here
    LDA $084B   ; use "a"
    PHA         ; -> optimize
    PLA         ; -> optimize
    STA $0400   ; POKE $0400,a

    LDA $084C   ; use "b"
    PHA         ; -> optimize
    PLA         ; -> optimize
    STA $0401   ; POKE $0401,b
    RTS
```
There are my own notes included, but I found out that XCBasic seems to compile a lot of pha-pla-pairs. It is only 2 bytes per pair, but it adds 7 cycles to execution time. Could those be removed?

**Comment by JJFlash-IT** [comment]
Hey there!
I know, I'm not neilsf, but I got curious about this, because I once had a look at how XCB3 produces the assembly code for DASM, and I saw through the so-called "list" file that it normally does most of the optimizations you mentioned.

I compiled your sample program, and then disassembled it through C64Studio, and this is what I see.
```
* = $0801
$0801:!byte $0B,$08,$E5,$07,$9E,$32,$30,$36
$0809:!byte $31,$00,$00,$00
$080D:  A9 FF      lda #$ff
$080F:  85 15      sta $15
$0811:  A9 00      lda #$00
$0813:  85 0F      sta $0f
$0815:  A9 CF      lda #$cf
$0817:  85 10      sta $10
$0819:  A5 01      lda $01
$081B:  29 FE      and #$fe
$081D:  85 01      sta $01
$081F:  A9 18      lda #$18
$0821:  8D 43 08   sta $0843
$0824:  A9 03      lda #$03
$0826:  8D 44 08   sta $0844
$0829:  20 35 08   jsr label_0835
$082C:  A5 01      lda $01
$082E:  09 01      ora #$01
$0830:  85 01      sta $01
$0832:  6C 02 A0   jmp ( $a002 )
$0835: 
$0835: label_0835
$0835:  AD 43 08   lda $0843
$0838:  8D 00 04   sta $0400
$083B:  AD 44 08   lda $0844
$083E:  8D 01 04   sta $0401
$0841:  60         rts
$0842:!byte $00
```
Most of the optimizations you were proposing are already there. The parts regarding location $01 are fixed parts (part of the "runtime library").

The optimizer can be disabled through an option parameter of the compiler. So I'm wondering if you disabled the optimizer by any chance?

```
  -p
  --optimize        Output optimized (faster and smaller) code. Turned on by default (true).
```

**Comment by orlof** [comment]
Hmmm, I already tried this with and without -p option, but still got those pha-pla pairs. Now I tried to compile directly from command line and it works as expected (no pha-pla). Which means that there is something wrong in my vscode build script. Sorry for the hassle.

**Comment by orlof** [comment]
OMG I finally realised that I was all the time editing the build script of a git subtree instead of the main program. That is why -p option seemed to have no effect  😆
