### ISSUE TITLE
ERROR: Only strings are allowed in INPUT statement - Type's

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#20]
disk.bas:16.0: ERROR: Only strings are allowed in INPUT statement, got diskio
> exit status: 1

![image](https://user-images.githubusercontent.com/14124210/147458625-7c87a68c-55d8-4a89-a88f-adf7206cd917.png)

![image](https://user-images.githubusercontent.com/14124210/147458667-97fe4018-a5f7-4b6c-ab4d-2bd31f6475a9.png)
[disk.zip](https://github.com/neilsf/xc-basic3/files/7779564/disk.zip)

**Comment by jakebullet70** [comment]
A note: In BASIC the THIS would be changed to ME.

**Comment by neilsf** [comment]
Looks like a bug, I'll check this. Thanks.
PS: In Visual Basic classes, yes, it's called `Me`. In other dialects, e.g Freebasic, it's called `THIS`.

**Comment by neilsf** [comment]
Fixed.
