### ISSUE TITLE
Option to select optimizations

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#200]
Now that I was able to turn on optimizer 😄 I find my program crashing... a lot. 
It would be useful if I could enable/disable specific optimizations to track what causes the crashes.

**Comment by neilsf** [comment]
There are only two kinds of optimization passes:
1) Use registers instead of the stack where possible
2) Replace some code sequences with faster equivalents
I wonder if it would be any helpful to en/disable them separately.

**Comment by orlof** [comment]
Ok, in that case it wouldn't provide that much value.
