### ISSUE TITLE
Stack cleanup error with optimizer

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#201]
I have this code
```
SUB PlayerUpdate() SHARED STATIC
    POKE 1024,1
    IF GameFuel > 0d THEN
    END IF
END SUB
```
Left side shows code with optimizer and right side shows without optimizer. As you can see optimizer removes one pla before rts and thus leaves the stack dirty for RTS.
![image](https://user-images.githubusercontent.com/1869202/186660850-3279cd8e-2ab8-46b1-b75f-b4ff1ab3e0a1.png)

**Comment by orlof** [comment]
...this also makes the IF to be evaluated incorrectly as Z flag comes from INX instead of PLA.

**Comment by neilsf** [comment]
Does it work if you add some body to the `IF` block? Honestly I never tested `IF ... END IF` without statements in between...
E. g
```
IF GameFuel > 0d THEN
  PRINT "test"
END IF
```

**Comment by orlof** [comment]
I added POKE 1025,1 inside the IF block, but it does not make any difference - stack is still broken.

```
.C:778e  AD C5 8A    LDA $8AC5
.C:7791  48          PHA
.C:7792  AD C6 8A    LDA $8AC6
.C:7795  48          PHA
.C:7796  A9 00       LDA #$00
.C:7798  48          PHA
.C:7799  A9 00       LDA #$00
.C:779b  48          PHA
.C:779c  BA          TSX
.C:779d  BD 02 01    LDA $0102,X
.C:77a0  DD 04 01    CMP $0104,X
.C:77a3  BD 01 01    LDA $0101,X
.C:77a6  FD 03 01    SBC $0103,X
.C:77a9  90 04       BCC $77AF
.C:77ab  A9 00       LDA #$00
.C:77ad  F0 02       BEQ $77B1
.C:77af  A9 FF       LDA #$FF
.C:77b1  9D 04 01    STA $0104,X
.C:77b4  E8          INX
.C:77b5  E8          INX
.C:77b6  E8          INX
.C:77b7  9A          TXS                         ; <== PHA still missing in here
.C:77b8  D0 03       BNE $77BD
.C:77ba  4C C2 77    JMP $77C2
.C:77bd  A9 01       LDA #$01
.C:77bf  8D 01 04    STA $0401
.C:77c2  60          RTS

```

**Comment by neilsf** [comment]
This one is fixed now. Do you have other bugs when you enable the optimizer? I won't close this issue until they're resolved.

**Comment by orlof** [comment]
This bug was kind of blocking more testing, but I will continue today...

**Comment by orlof** [comment]
I compiled xc-basic and tried to compile my basic program with it, but it seems that I have used variable names (e.g. hires) that are reserved words in 3.1. It will take a while to get my program 3.1 compatible.

**Comment by orlof** [comment]
With all the new reserved words [#190](https://github.com/neilsf/xc-basic3/issues/190) is biting me pretty hard...

**Comment by neilsf** [comment]
Actually HIRES is now a reserved word but it shouldn't be... I'll review the list of reserved words and only keep those necessary.

**Comment by orlof** [comment]
I have now hundreds of naming conflicts because my custom type fields and parameters in custom type SUBs start with some of the new reserved words e.g. Color, Hires, At, Clear... there is a lot.

**Comment by neilsf** [comment]
Those identifiers are valid, so this is an issue with the grammar parser. Working on it.

**Comment by neilsf** [comment]
I've added a lot of grammar improvements. Unfortunately they don't solve  #190 yet, but at least variable names like `Color0` are working.

@orlof Can you please try to comple your program and let me know about any other false errors? Many thanks

**Comment by orlof** [comment]
I am impressed with the improved grammar. That was a huge help . Thanks!

This time everything worked like a charm. No compilation errors, no runtime glitches in my test runs. Enabling the optimizer saved me 4473 bytes. Fantastic!
