### ISSUE TITLE
[ALPHA 3.1] How do raster interrupts work? 

### ISSUE THREAD

**Issue by Diduz** [neilsf/xc-basic3#203]
Hello, I had implemented a nice way to create a status bar for my text adventure game in XC-Basic v. 2.3. I used the xcb-ext-rasterinterrupt extension. This was my old and working routine to handle the effect. ;-) Check the first screenshot.

```

include "xcb-ext-rasterinterrupt.bas"

dim quest![5]
question$=@quest!

proc fixedline
poke 53272,( peek(53272) & 15) | 16
rem screen ram 1 to host the fixed line
endproc

proc otherlines
poke 53272,( peek(53272) & 15) | 240
rem screen ram 15 to host all the other lines
endproc

print "{CLR}"

poke 53280,0 : poke 53281,0

ri_isr_count! = 2
ri_set_isr 0, @fixedline, 0
ri_set_isr 1, @otherlines, 60

ri_on

poke 648, 4
print "{CLR}";
print "{REV_ON}this is the fixed line{REV_OFF}"
poke 648, 60
print "{CLR}"
curpos 0,3
dilemma:
print "these are all the other lines"
print "is it ok with you?"
input question$, 4 : print""
if strcmp(question$,"ok")=0 then goto happyend
goto dilemma
happyend:
ri_off
print "{CLR}"
print "i am glad you got it!"
end
 
```

![01](https://user-images.githubusercontent.com/39902698/188327069-10cdac0a-1ecb-43bd-b4d6-8449dc82e284.png)

When I tried and convert this code for version 3.1, I used the new interrupts commands, but unfortunately they don't trigger the effect. Am I using the new commands in the right way? Here's the same little program converted in v. 3.1. Check the second screenshot. The "status bar" is not there. I even tried to use the SCREEN command instead of POKES, but I get a garbled result (that's not even what I need, I just need to switch the screen ram position). Perhaps I'm wrong to think the RASTER INTERRUPT commands work as they did in the 2.3 extension...?

```

DIM question as string * 4

print "{CLR}"

BORDER 0 : BACKGROUND 0

ON RASTER 0 GOSUB fixedline
ON RASTER 60 GOSUB otherlines

RASTER INTERRUPT ON

poke 648, 4
print "{CLR}";
print "{REV_ON}this is the fixed line{REV_OFF}"
poke 648, 60
print "{CLR}"
locate 0,3
dilemma:
print "these are all the other lines"
print "is it ok with you?"
input question
if question="ok" then goto happyend
goto dilemma
happyend:
RASTER INTERRUPT OFF
print "{CLR}"
print "i am glad you got it!"
end
 
fixedline:
POKE 53272, (PEEK(53272)AND15)OR16 : rem screen ram 1 to host the fixed line 
return

otherlines:
POKE 53272, (PEEK(53272)AND15)OR240 : rem screen ram 15 to host all the other lines 
return


```

![02](https://user-images.githubusercontent.com/39902698/188327076-79895315-204e-4c9c-920f-8f154e6bba4a.png)

**Comment by neilsf** [comment]
Hi
This is not going to work:

     ON RASTER 0 GOSUB fixedline
     ON RASTER 60 GOSUB otherlines

because the second one overwrites the first one. However, you can change the raster line and the handler routine at the end of the routines, like this:

     fixedline:
     POKE 53272, (PEEK(53272)AND15)OR16 : rem screen ram 1 to host the fixed line
     ON RASTER 60 GOSUB otherlines
     return

     otherlines:
     POKE 53272, (PEEK(53272)AND15)OR240 : rem screen ram 15 to host all the other lines
     ON RASTER 0 GOSUB fixedline
     return

I'm also not sure that `poke 648, xx` will work in XC=BASIC (maybe it does). Did you try `SCREEN` ?

**Comment by Diduz** [comment]
Thanks, it works now!
I notice there's some sporadic flickering on the first of the "other lines", though.
Is there a reason why there was no flickering with the old 2.3 extension?
Could timer interrupts help here?

> I'm also not sure that `poke 648, xx` will work in XC=BASIC (maybe it does). Did you try `SCREEN` ?

I can confirm "poke 648,xx" works fine. ;-) I also tried "SCREEN x" in irqservs and I cannot see any difference.

**Comment by neilsf** [comment]
> Is there a reason why there was no flickering with the old 2.3 extension?

Yeah, that extension didn't provide safe interrupts, which means you could easily run into a situation where XC=BASIC virtual registers are messed up (e. g both the main program and the interrupt service routine write to them). In version 3.1, those registers are pushed onto the stack before the service routine is passed control to, which takes a considerable amount of time (actually, hundreds of CPU cycles).

More information: https://xc-basic.net/doku.php?id=v3:interrupts

**Comment by neilsf** [comment]
I've just added a new option that allows you to use fast interrupts, i. e. the runtime will not care about saving virtual registers, making interrupt service routines start much faster. You can try this example:

    OPTION FASTINTERRUPT
    GOSUB r3
    
    SYSTEM INTERRUPT OFF
    RASTER INTERRUPT ON
    
    l: GOTO l
    
    r1:
      BORDER 1 : BACKGROUND 1
      ON RASTER 120 GOSUB r2
      RETURN
      
    r2:
      BORDER 2 : BACKGROUND 2
      ON RASTER 130 GOSUB r3
      RETURN
      
    r3:
      BORDER 3 : BACKGROUND 3
      ON RASTER 100 GOSUB r1
      RETURN

**Comment by Diduz** [comment]
> I've just added a new option that allows you to use fast interrupts, i. e. the runtime will not care about saving virtual registers, making interrupt service routines start much faster. 

Wow, I'm speechless. I'll give it a try as soon as possible! I had just found a "sweet spot" without flickering at raster line 50, but unfortunately this solution puts the "otherlines" too close to the "fixed line": not too elegant. :-P
I'll try this new "unbridled" option and see what happens. Considering my code worked with the old 2.3 extension, I feel optimistic. I'll let you know! :-)
I guess I'll have to learn how to read the machine monitor in VICE, to check the zero page...

**Comment by Diduz** [comment]
No, I think FASTINTERRUPT doesn't help in this case. Strings get truncated, incomplete or garbled. I guess this code needs the standard, "calm" virtual registers. Never mind, At least I triggered a new feature for XC-Basic! :-)

**Comment by neilsf** [comment]
> Strings get truncated, incomplete or garbled.

What about printing the strings first and turning on interrupts only after that?

**Comment by Diduz** [comment]
> > Strings get truncated, incomplete or garbled.
> 
> What about printing the strings first and turning on interrupts only after that?

I have another idea, but for some reason I can't modify color ram any longer.
I wanted to change the color of text in the second line, but "memset 55336, 40, 0" doesn't seem to work. Nothing happens (with or without interrupts, I also tried that in a simpler program).

**Comment by neilsf** [comment]
`MEMSET 55336, 40, 0` works for me as intended.
