### ISSUE TITLE
[ALPHA 3.1] Out of zeropage addresses

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#205]
Hmmm... I am pretty sure I have 48 bytes worth of variables declared AS FAST

According to memory model there should be 61 bytes available for FAST variables. Still I am getting this compiler warning:

`main.bas:169.0: WARNING: Out of zeropage space, ignoring FAST option for variable gametime
`

**Comment by neilsf** [comment]
As the documentation states, the user ZP area is subject to change. In 3.1-alpha, it's only 46 bytes.

**Comment by orlof** [comment]
This is not a super important issue, but I am making a game without any possibility to return back to basic. Would it be a problem to enable larger ZP area with e.g. compiler option?

**Comment by neilsf** [comment]
Does your program use Floating Point? FP registers reserve 37 bytes which could be utilized.

**Comment by orlof** [comment]
No, I don't use FPs. What is the address range for those registers - Is it the standard e.g. 87-114? I am happy to repurpose those.

**Comment by neilsf** [comment]
Actually, you can put your variables anywhere using the @ operator. E. g `DIM gametime AS WORD @$70`

**Comment by orlof** [comment]
I can do that. I wouldn't mind the compiler option to "disable" floats, but @ operator works also.

**Comment by neilsf** [comment]
Closing this as the requirement can be worked out in user code.
