### ISSUE TITLE
READ and WRITE with array elements

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#207]
Should this work?

```
DIM arr(2) AS BYTE
arr(0) = 5
arr(1) = 6

OPEN 1,8,2,"test,s,w"
WRITE #1, arr(0)
WRITE #1, arr(1)
CLOSE 1

DIM arr2(2) AS BYTE

OPEN 1,8,2,"test,s,r"
READ #1, arr2(0)
READ #1, arr2(1)
CLOSE 1

PRINT arr(0), arr(1)
PRINT arr2(0), arr2(1)
```

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/1869202/189583001-ee03bd1c-018b-4d53-9893-c60a11255d3b.png">

**Comment by neilsf** [comment]
It should and with the above fix it works :-)

**Comment by orlof** [comment]
I am still getting wrong results (but different). I think this bugfix should already be in the binaries also...
<img width="634" alt="image" src="https://user-images.githubusercontent.com/1869202/190925955-1bae4c2a-69ba-4597-8740-776ce5cffc15.png">

**Comment by neilsf** [comment]
Did you update the files in `lib/` as well?

**Comment by orlof** [comment]
I did `git pull` for release/v3.1

**Comment by neilsf** [comment]
Interesting.... it works for me

**Comment by JJFlash-IT** [comment]
I'm sorry for lowering @orlof 's mood even more, but... it works for me too, on Windows no less! 😃 

![Clipboard01](https://user-images.githubusercontent.com/48549431/191190548-e813a732-a8e8-4edb-9704-cfbf03a08438.png)

(I got the 18/09/2022 branch through the "boomer way", "Download ZIP" from the release/v3.1 branch)

**Comment by orlof** [comment]
After scratching my head for 30 minutes - deleting, cloning, setting paths, configuring editor, changing VICE -> it suddenly started to work. I still don't know what fixed it, but the problem was clearly in my setup.
