### ISSUE TITLE
[Alpha 3.1][minor parser issue] Identifier that starts with a reserved word, followed by any number of digits, triggers a Syntax Error

### ISSUE THREAD

**Issue by JJFlash-IT** [neilsf/xc-basic3#208]
> XC=BASIC compiler version v3.1.0-alpha-0 (Sep 11 2022)

```
dim screen1 as BYTE
dim for2 as BYTE
dim print33 as BYTE
dim loop456 as BYTE
```
Any identifier with a pattern like that - reserved word followed immediately by one or more digits - triggers a Syntax Error.

```
dim screen_1 as BYTE
dim fora2 as BYTE
dim printt33 as BYTE
dim loops456 as BYTE
dim manyLoop5 as BYTE
```
Those don't produce any error and the compilation completes successfully.

Maybe this needs some finetuning in some grammar/parsing rule?

**Comment by neilsf** [comment]
Thanks @JJFlash-IT - fixed now. The fix will be included in the next minor release.
