### ISSUE TITLE
Implement INSTR()

### ISSUE THREAD

**Issue by neilsf** [neilsf/xc-basic3#21]
Similarly to https://wiki.qb64.org/wiki/INSTR

**Comment by Diduz** [comment]
Hi! :-) Are you still planning this feature for v. 3.1? It's pretty useful for text adventures :-P (STRPOS function in v. 2.3 was fine).
Thanks for all your work, Csaba!

**Comment by neilsf** [comment]
Hi
It's planned for v3.1 but not yet implemented. Here's the BASIC implementation, you can try this:

    FUNCTION INSTR AS BYTE (haystack AS WORD, needle AS WORD) SHARED STATIC
      hlen = PEEK(haystack) : nlen = PEEK(needle)
      haystack = haystack + 1 : needle = needle + 1
      IF nlen > hlen THEN RETURN 0
      FOR i AS BYTE = 0 TO hlen - nlen
        FOR j AS BYTE = 0 TO nlen - 1
          IF PEEK(haystack + i + j) <> PEEK(needle + j) THEN EXIT FOR
        NEXT j
        IF j = nlen THEN RETURN 255
      NEXT i
      RETURN 0
    END FUNCTION
    
    ' Tests
    DIM a$ AS STRING * 4
    DIM b$ AS STRING * 2
    DIM c$ AS STRING * 3
    a$ = "abcd" : b$ = "bc" : c$ = "cd"
    PRINT INSTR(@a$, @b$)
    PRINT INSTR(@b$, @a$)
    PRINT INSTR(@a$, @c$)

**Comment by Diduz** [comment]
Thanks! :-)

**Comment by neilsf** [comment]
Cancelling this. The feature can be added as user code.
