### ISSUE TITLE
INPUT doesn't inhibit endless BACKSPACE

### ISSUE THREAD

**Issue by Diduz** [neilsf/xc-basic3#210]
This happens in ALPHA 3.1 (C64 target), I don't know if 3.0 is affected too.
If the user keeps pressing BACKSPACE when asked for INPUT, cursor is free to erase the whole screen. The same happens in C64 BASICV2 by default, but in v.2.3 you couldn't backspace beyond the INPUT prompt.
I know it's a minor issue, but I think that backspacing is more elegant when contained within the INPUT line. ;-)

**Comment by neilsf** [comment]
Version 3 in general, especially v3.1 tries to rely on KERNAL as much as possible for cross-platform compatibility. This means that the custom solutions used in version 2 are now replaced with standard KERNAL calls.

As in CBM BASIC, you have to implement your own solution if the built-in routines don't fit your needs.
