### ISSUE TITLE
[alpha 3.1] On-Goto complains about missing labels that are actually present, when used in sub/function with a parameter whose type is not explicitly defined

### ISSUE THREAD

**Issue by JJFlash-IT** [neilsf/xc-basic3#211]
> XC=BASIC compiler version v3.1.0-alpha-0 (Sep 18 2022)
```
function init_charset as BYTE(animphase) STATIC
	on animphase goto init_1, init_2

init_1:
init_2:
	return animphase
end function
```
With this code, XCB doesn't complain about the missing type definition in the function parameter (animphase), but then throws an error on the on-goto line saying `Label does not exist: init_1` , but it's actually there.

Same thing happens using a Sub instead of a Function.

Adding an explicit type to animphase (can be BYTE, INT, WORD, ...) lets XCB compile the code.

I tried to use Select Case and there were no problems, so it seems to be something specific with On-Goto (or, maybe better, with labels).

**Comment by neilsf** [comment]
Parameter type definition is mandatory - so it looks like the bug is actually the compiler allowing you to write parameters without an explicit type.
