### ISSUE TITLE
[3.1] RND() not working properly on first call

### ISSUE THREAD

**Issue by sine707** [neilsf/xc-basic3#217]
The usage of `rnd()` when called for the first time leads to weird behaviour. All subsequent calls seem to be working fine though.
Tested with and without `randomize ti()`.

```
print rnd()
print rnd()
print rnd()
print rnd()
print rnd()
print rnd()
```

Possible outputs:
```
.a70315
.972985
.841289
.556634
.663281
.42369
```
or
```
.@03247
.486737
.548671
.566067
.098523
.26513
```
or

```
.d29238
.441768
.0201512
.698348
.914749
.452402
```

**Comment by neilsf** [comment]
There's a bug in the `PRINT <float>` command that outputs wrong characters at first call. Here's how to reproduce:

a = 0.12345
PRINT a
PRINT a

The second call to `PRINT a` works correctly.
