### ISSUE TITLE
Set the length of a string by assigning a value to it

### ISSUE THREAD

**Issue by mrg-75** [neilsf/xc-basic3#23]
At the moment you have to set the length of a string, and then give a value:

`dim myString as string * 9`
`myString = "some text"`

It would be a nice feature if it could be done in one line, something like
`dim myString as string = "some text"`

Or possibly even `dim myString as "some text` with the compiler detecting it's a string, and setting the length automatically.

**Comment by neilsf** [comment]
I was planning something similar, but dropped the idea bc of lack of time.
My idea was to allow implicit definition of strings if the initial value is constant. For example:
`mystr$ = "some text"`
without the DIM.
I can implement this if I have some time later.

**Comment by jakebullet70** [comment]
I like the DIM.  
**Dim mystr$ = "some text"**
Would also like
Dim id, ndx, idx as byte = 255

**Comment by neilsf** [comment]
> I like the DIM.

IMHO `DIM` should not be used for value assignment. We have `LET` (with our without the keyword) for that purpose.

`DIM a, b, c, d AS type`

would be useful though.
