### ISSUE TITLE
Add shift operators

### ISSUE THREAD

**Issue by AGPX** [neilsf/xc-basic3#230]
Please add shift operators on left and right to allow fast multiplication and division.

**Comment by JJFlash-IT** [comment]
Please read the documentation, they've been there for a long time :)

https://xc-basic.net/doku.php?id=v3:shl
https://xc-basic.net/doku.php?id=v3:shr

**Comment by AGPX** [comment]
I read it and couldn't find it easily. I expected to find them among the operators, but they weren't there.

**Comment by neilsf** [comment]
It would make sense to put links to these functions on the Operators page. Will do that.
