### ISSUE TITLE
DATA syntax for two-dimensional array?

### ISSUE THREAD

**Issue by sine707** [neilsf/xc-basic3#235]
Is it currently possible to populate a two-dimensional array with DATA?
I wasn't able to find it in the docs and my experiments have failed thus far.
```
dim test_values(3, 3) as byte @testdata

testdata:
data as byte ???
```

**Comment by neilsf** [comment]
Two dimensional arrays are nothing more than linear data.

Try this:

    DIM testvalues(3,3) AS BYTE @testdata
    
    FOR i AS BYTE = 0 TO 2
      PRINT testvalues(0, i), testvalues(1, i), testvalues(2, i)
    NEXT i
    
    testdata:
    DATA AS BYTE 1, 2, 3
    DATA AS BYTE 4, 5, 6
    DATA AS BYTE 7, 8, 9
    
    ' Note that the following is identical
    ' DATA AS BYTE 1, 2, 3, 4, 5, 6, 7, 8, 9

**Comment by sine707** [comment]
Thank you!
I had the order wrong, as I was thinking `testvalues(index, value)` instead of the other way around.
This makes sense now.

**Comment by neilsf** [comment]
I'm glad that I could help. It might not be intuitive how array elements are laid out in memory, but it is what it is.
