### ISSUE TITLE
Bug with the LONG type

### ISSUE THREAD

**Issue by AGPX** [neilsf/xc-basic3#238]
Hi again,

I'm stuck with a project in XC=Basic (I'm the author of the Pac-Man and Labyrinth-3D) due to a bug in the compiler. If you try the following code:

```
DIM A AS LONG, B AS LONG, C AS LONG

A = 0
B = 12000
C = 3000
PRINT (A - B) / C
```

It should print -4, but instead it print 4. If you replace LONG with INT, the result is correct (looks like that the division is the problem, because A - B is printed correctly as -12000).

Please support.

**Comment by JJFlash-IT** [comment]
Tried this myself, apparently it's something specific with division, all the other operations seem to work fine.

**Comment by AGPX** [comment]
Please double check how the sign is handled.

**Comment by neilsf** [comment]
Yes, the bug was in LONG division.

**Comment by neilsf** [comment]
Please download v3.1.9

**Comment by AGPX** [comment]
A new XC=Basic tech demo is coming, stay tuned :-)

**Comment by neilsf** [comment]
Cool! Keep us updated. Thanks.

**Comment by AGPX** [comment]
> Cool! Keep us updated. Thanks.

Here it is: [https://www.youtube.com/watch?v=FLPNtlsF5rw](https://www.youtube.com/watch?v=FLPNtlsF5rw)
