### ISSUE TITLE
avoid DECLARE SUB / FUNCTION 

### ISSUE THREAD

**Issue by nippur72** [neilsf/xc-basic3#241]
Why there's need to DECLARE SUB or FUNCTION...? can just the compiler figure it out by himself by doing another extra pass?

**Comment by JJFlash-IT** [comment]
In its defense I'll say that it's not an XC=BASIC "exclusive", there are quite a few modern BASIC dialects (and also other programming languages, like C if I'm not mistaken?) where you are required to declare SUBs, FUNCTIONs and the like if you define them _after_ using them for the first time.

I don't find it particurarly struggling to just define everything before they're first called. Also, as I said, it's pretty standard stuff.

**Comment by neilsf** [comment]
`xcbasic3` is a multipass compiler so theoretically it could read function headers in an early pass. I'll see how difficult it is to implement but for now I don't think that forward declaration is a big pain, especially that QBasic (our quasi-reference language) also requires it.
