### ISSUE TITLE
Dasm

### ISSUE THREAD

**Issue by jacopo-jack** [neilsf/xc-basic3#248]
Some time  appears this bug  during the compilation: recognized as an internal or external command,
 an executable program or batch file.

**Comment by neilsf** [comment]
It means your shell cannot find _dasm.exe_ (looking at the error message I'm assuming you're using Windows)
Here are your options

- You [add it to your PATH](https://medium.com/@kevinmarkvi/how-to-add-executables-to-your-path-in-windows-5ffa4ce61a53)
- You tell `xcbasic3` where _dasm.exe_ is. For example. `xcbasic3 -d C:\path\to\dasm.exe sourcefile.bas output.prg`
