### ISSUE TITLE
SPRITE n ON BACKGROUND does not work

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#249]
```
MEMSET 12288, 64, 255

SPRITE 0 SHAPE 192 AT 100,50 COLOR 1 HIRES ON BACKGROUND ON
SPRITE 1 SHAPE 192 AT 124,50 COLOR 2 HIRES UNDER BACKGROUND ON
```

<img width="445" alt="image" src="https://github.com/neilsf/xc-basic3/assets/1869202/d992372a-4077-4b77-9f67-5e2ed02aa484">

Perhaps parser confuses options `ON` and `ON BACKGROUND` (at least my VSCode extension does 😆 ). One option would be to use `OVER BACKGROUND` instead.

**Comment by phaze101** [comment]
Yes I have also experienced same thing. I think it gets confused with ON.
