### ISSUE TITLE
Compile error -1073741819

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#25]
![image](https://user-images.githubusercontent.com/14124210/147907422-f2d88b42-2ce0-47db-9f10-3a4f77fc97f6.png)
[strhelper.zip](https://github.com/neilsf/xc-basic3/files/7800772/strhelper.zip)

**Comment by neilsf** [comment]
Good old segfault :-) I'll debug this, thanks!

**Comment by neilsf** [comment]
It is because you're using the THIS keyword outside a TYPE block. The compiler should stop here with a human readable error message rather than segfaulting.
