### ISSUE TITLE
Question: ZP for FP?

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#251]
I am reusing the ZP addresses reserved for fp operations. The documentation at https://xc-basic.net/doku.php?id=v3:memory_model says they are location in $15 - $3a, but it seems that the XCBasic3 preample zeroes addresses $16 - $3b.

I just want to verify that documentation is correct?

**Comment by neilsf** [comment]
Hi @orlof 
It's indeed starting at $16. I've updated the docs. Thanks for bringing it to my attention.
