### ISSUE TITLE
SPRITE XYSIZE x and y are in wrong order

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#252]
`MEMSET CWORD(192)*64, 64, $ff

SPRITE 0 AT 100,100 XYSIZE 1,0 SHAPE 192 ON
SPRITE 1 AT 150,100 XYSIZE 0,1 SHAPE 192 ON
`

<img width="683" alt="image" src="https://github.com/neilsf/xc-basic3/assets/1869202/88affc4e-0f31-42fb-a238-38fa8ab33373">

**Comment by neilsf** [comment]
Thanks for reporting. It will be fixed in a new release soon.
