### ISSUE TITLE
Fail to find DASM - Commander X16

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#260]
Finnally found some energy to look at the X16 support and ran into this issue. What stupid thing did I do?  :)
I did notice that X16 support is dated end of 2022.

Error:
![image](https://github.com/neilsf/xc-basic3/assets/14124210/59e47c8c-4340-4b80-9ccf-2ec3329a70bc)

Folders:
![image](https://github.com/neilsf/xc-basic3/assets/14124210/2b7d4a3d-93cd-4f0b-b407-68cdcec14519)

**Comment by neilsf** [comment]
Hi @jakebullet70 
XC=BASIC uses the dasm assembler.
Have you installed _dasm.exe_ and is it in your `%PATH%` environment variable?
Alternatively, you can just put _dasm.exe_ in the folder where you invoke the command.

**Comment by jakebullet70** [comment]
Thought I had it in path but it was not. All is good now. Closing this
