### ISSUE TITLE
Size optimization: Do not include unreachable routines & functions

### ISSUE THREAD

**Issue by kochs-online** [neilsf/xc-basic3#273]
Same, but different as #2:

Sub routines that are unreachable (based on static code analysis) are currently part of the compiler output.

Please consider this code:
```basic
CONST ASSERTS = $00

SUB assert (condition AS BYTE, message AS STRING * 20) STATIC
END SUB

IF ASSERTS THEN
  CALL assert(1 = 2, "")
END IF
```
Sub routine `assert()` is unreachable because the condition of the preceding `IF` statement statically evaluates to `false`. However the currently resulting program segments look like this:
```
+---------------+-------+-------+
|    Segment    | Start |  End  |
+---------------+-------+-------+
|BASIC Loader   | $0401 | $040C |
|Program code   | $040D | $0459 |
|Library        | $045A | $049F |
|Data & Strings | $04A0 | $04A0 |
|Variables*     | $04A1 | $04B7 |
+---------------+-------+-------+
```
Not only is the sub routine part of the program code segment, but there is also code for a jump to this (empty) sub routine:
```asm
                    lda #$00    ; constant ASSERTS
                    bne L0429   ; process parameters for sub routine
                                ; and call sub routine [S0459]
                    jmp L0456   ; jump to end of program (and back to BASIC)
L0429               […]         ; parameter processing
                    jsr S0459
                    […]
S0459               rts         ; (empty) sub routine assert()
```
Further optimization might include evaluation of constant values like `1 = 2` from the example above.
Currently this results in this assembler code:
```asm
L0429               lda #$01
                    cmp #$02
                    beq L0433
                    lda #$00   ; FALSE
                    beq L0435
L0433               lda #$ff   ; TRUE
L0435               […]
```

**Comment by neilsf** [comment]
Hi there.
Unreferenced subs/functions are not included in the final binary. The sub in your example is referenced, this is why it is compiled.
Preprocessor directives would solve this problem (note the `#` before `IF` and `END IF`):

````
#IF ASSERTS THEN
  CALL assert(1 = 2, "")
#END IF
````

XC=BASIC doesn't provide a preprocessor yet. It is planned for a future version.

**Comment by kochs-online** [comment]
> XC=BASIC doesn't provide a preprocessor yet. It is planned for a future version.

That would be a valuable feature!

> Further optimization might include evaluation of constant values like `1 = 2` from the example above.

Is there any approach to this? This applies to `DIM` variables as well:
```basic
DIM n AS WORD
n = 8 * 4 * 25
```
This example will produce Assembler/ML code that is calculating the [constant] result of 800 while a simple assignment would save memory space and significantly improve performance.

Another improvement would be to allow calling functions without assigning the returned value if we don't care for it. As of now the compiler throws syntax errors:
```basic
FUNCTION write_log(msg AS STRING * 40)
  […]
  RETURN success   ' $FF if successful; $00 if failed to write log
END FUNCTION

write_log("5349 MODE COMPLETE")   ' compiler output: "ERROR: Syntax error"
```

**Comment by neilsf** [comment]
As for compile time expression evaluation, see my comment here: https://github.com/neilsf/xc-basic3/issues/240#issuecomment-1704027864

Unfortunately, the design decision has not been yet made. Any input/opinion is welcome.

> Another improvement would be to allow calling functions without assigning the returned value if we don't care for it. 

I think in this case you should define a `SUB` instead of a `FUNCTION`.

**Comment by kochs-online** [comment]
> As for compile time expression evaluation, see my comment here: [#240 (comment)](https://github.com/neilsf/xc-basic3/issues/240#issuecomment-1704027864)
> 
> Unfortunately, the design decision has not been yet made. Any input/opinion is welcome.

Very good point indeed! I did not consider the different behavior of host and target platform.
