### ISSUE TITLE
Issue with reading the disk drive.

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#28]
** Wonder if we still have a bug in the drive commands.  Or... Just me being stupid.
Converted this code to xc-basic and its not working.

![image](https://user-images.githubusercontent.com/14124210/148074601-d27f1246-054c-462a-859d-47687053bfa3.png)
[disktype.zip](https://github.com/neilsf/xc-basic3/files/7808275/disktype.zip)

**Comment by neilsf** [comment]
This is wrong:
`dim hi as int : hi = int(a / 256)`
You're doing an integer division and then convert it to floating point. It doesn't make sense.
Try something like this:
```
DIM a AS WORD : a = 65331
DIM hi AS BYTE : hi = CBYTE(SHR(a, 8))
DIM lo AS BYTE : lo = CBYTE(a)
```
but since 65331 is a constant, you can avoid all the calculations and simply do: `hi = 255 : lo = 51`

**Comment by jakebullet70** [comment]
Thanks @neilsf, I am going to have to pay more attention. I am closing the bug. On the bright side we now have a code snippet to get the Commodore drive type!
