### ISSUE TITLE
XC=BASIC library was not found in "/usr/lib

### ISSUE THREAD

**Issue by DannyCork** [neilsf/xc-basic3#29]
Using Mac Monterey 12.1

So I created a symbolic link to xcbasic3 as directed

```
$ sudo ln /Users/x/source/xc-basic3/bin/macOS/xcbasic3 /usr/local/bin/xcbasic3

$ ls -la /usr/local/bin/xcbasic3 
-rwxr-xr-x  2 d  staff  16329472 Jan  4 23:01 /usr/local/bin/xcbasic3
```

/usr/local/bin is in my path.

However when I execute xcbasic complains about the lib folder missing
```
$ xcbasic3 
XC=BASIC library was not found in "/usr/lib". Please make sure the directory exists and contains the library files.
```

I've left the lib folder in the original location as advised here https://xc-basic.net/doku.php?id=v3:installation_and_usage
`To run properly, XC=BASIC needs the lib/ directory as well and it must be in the same folder where the bin/ directory is. Just leave them as they are.
`

Is /usr/lib hardcored as xc basic appears to be expecting the libs there?

**Comment by neilsf** [comment]
> Is /usr/lib hardcored as xc basic appears to be expecting the libs there?

No. XC=BASIC is trying to find the `lib/` directory at `../../lib` relative to the executable. It is coded to recognize if the exacutable is behind a symbolic link so it's strange why it doesn't work on Mac. I'll try to debug this. In the meantime please try without the link, it should work that way.

**Comment by neilsf** [comment]
Are you using the latest (beta) version?

**Comment by DannyCork** [comment]
Thanks for the info. Removing the symbolic link works just fine as you suggested.

I am using the v3.0.0-beta1, last commit is :

commit f35fcdbc33c5688545bf643cb8d1a9fa3b41f870 (HEAD -> main, origin/main, origin/HEAD)
Author: github-actions <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Mon Jan 3 16:43:13 2022 +0000

    Commit from GitHub Actions (Build project)

**Comment by neilsf** [comment]
Thanks for confirming.

**Comment by neilsf** [comment]
I've added a new build. I'm not sure if it fixes the bug cause I have no access to a Mac, can you please try?

**Comment by neilsf** [comment]
Closing this issue due to long (30 days) inactivity.

**Comment by gpowerf** [comment]
I had the same issue under Debian Bullseye, removing the symbolic link also fixed the problem.
