### ISSUE TITLE
Option to compile DATA statements at the current origin

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#35]
This is my first test with xc-basic, so there is a high probability that I have misunderstood something 😄 

This is the code
```
GOTO START

ORIGIN 2112
DATA AS BYTE 0,1,2,3,4,5,6,7

START:
DIM values(8) AS BYTE @2112
PRINT values(3)
```
Compiling and running this in VICE prints `32`, but I would expect it to print `3`. I also find the syntax `@2112` a little surprising (the need for `@` sign specifically).

**Comment by orlof** [comment]
Okey, it seems that the origin is not doing what I supposed it would do:
```
GOTO START

ORIGIN 2112
PTR:
DATA AS BYTE 0,1,2,3,4,5,6,7

START:
DIM values(8) AS BYTE @2112
PRINT values(3)
PRINT @PTR
```
Prints 2366 for the value of PTR address.

**Comment by orlof** [comment]
After a bit of debugging I figured that origin only affects the code - not data. Data seems to be located after code. Is that by design? 
I was testing if I could store e.g. sprite data before the code by using origin, but perhaps there is some better way to achieve it. 🤔

**Comment by neilsf** [comment]
Hi @orlof. Thank you for your feedback.

> After a bit of debugging I figured that origin only affects the code - not data.

Yes, DATA is assembled outside of the normal flow.

> I was testing if I could store e.g. sprite data before the code by using origin

You can do that using [INCBIN](https://xc-basic.net/doku.php?id=v3:incbin). It injects binary data at the current origin. As for DATA, I can add a command line option that enables inline DATA - meaning it is assembled at the current origin, rather than after code.

Let's keep this issue open.

**Comment by orlof** [comment]
That sounds good. Since DATA is effectively injecting values to memory - just like INCBIN, but visible in code - I would even consider that option to be the default. Unless there is some specific use case for moving DATA behind the code that I just don't know.

**Comment by neilsf** [comment]
> That sounds good. Since DATA is effectively injecting values to memory - just like INCBIN, but visible in code - I would even consider that option to be the default. Unless there is some specific use case for moving DATA behind the code that I just don't know.

The reason why DATA is outside of the code flow is to prevent accidental execution that would (most probably) lead to a crash. Nb. variables are also reserved at the end unless their addresses are implicit.

**Comment by neilsf** [comment]
I have added the _--inline-data_ option. I have also updated the documentation to explain the difference: https://xc-basic.net/doku.php?id=v3:data

**Comment by orlof** [comment]
Thanks, I tested it and seems to work perfectly!
I will close this issue, but I am still a bit confused why @ sign was needed in `DIM values(8) AS BYTE @2112`. E.g. POKE does not require @ sign before address.

**Comment by neilsf** [comment]
> but I am still a bit confused why @ sign was needed

Yes, this is a bit confusing. The @ sign has two different meanings:

1. To resolve the address of a variable or label, e.g @myVar will evaluate to the address where myVar is in memory.
2. In a DIM statement to explicitly set the address.

It might be confusing but had no better idea.

**Comment by orlof** [comment]
Ahh - I see. One option would be to use literal `AT` in DIM and reserve @ sign for evaluating the address of variables.
 ```
DIM values(8) AS BYTE AT 2112
DIM values(8) AS BYTE AT MY_LABEL
DIM values(8) AS BYTE AT @MY_VARIABLE
```
...I am just throwing ideas

**Comment by neilsf** [comment]
Since this syntax hasn't changed since a very early version and users have been happy with it, I would like to keep it as it is.
