### ISSUE TITLE
Using LEN on a string twice returns the wrong value

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#40]
![image](https://user-images.githubusercontent.com/14124210/149533267-5d317802-82e0-4c91-be7a-e7153d8bd9b2.png)
![image](https://user-images.githubusercontent.com/14124210/149533311-36d929e5-fa09-4b84-80b1-56949324635c.png)
[test.zip](https://github.com/neilsf/xc-basic3/files/7871043/test.zip)

**Comment by neilsf** [comment]
Odd, it works for me
![image](https://user-images.githubusercontent.com/5172851/149650863-3368edeb-c470-44d7-87d8-400f4a6d4104.png)
Are you using the latest compiler?

**Comment by orlof** [comment]
works for me also with 15.1.2022 build.

**Comment by neilsf** [comment]
Closing this now. @jakebullet70 please reopen if it still doesn't work for you after upgrading.
