### ISSUE TITLE
Crash when running in C64

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#42]
(Sorry, I originally posted this to XC-Basic project -> wrong one)
c64 consistently crashes when executing this code (I tried to isolate the problem into small snippet):

```
DIM i AS INT

SUB calc_mod(s0 AS INT, s1 AS INT) STATIC
    i = s0 MOD s1
END SUB

CALL calc_mod(0, 255)
```

**Comment by neilsf** [comment]
The same bug as #43 so I'm closing this. Thanks.
