### ISSUE TITLE
Something with manipulating the string return value of a function, doesn't work.

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#45]
I can't seem to adjust the return string directly. In the example below, the length of the string is always 0. It seems for the purpose of a poke, you can't reference `@str_Strings`. The value always seems to be 0 in the following example.

```basic
FUNCTION str_Strings AS STRING*96 (count AS BYTE, character AS BYTE) STATIC SHARED

  print peek(@str_Strings)
  POKE @str_Strings, count
  print peek(@str_Strings)

END FUNCTION
```

**Comment by neilsf** [comment]
This is a bug in the POKE command itself.
