### ISSUE TITLE
Consequtive RNDL calls repeat shifted bit patterns

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#49]
Consequent calls to rndl provide same values in bits 23:12 that were in 15:4 in previous call.
![image](https://user-images.githubusercontent.com/1869202/149650990-f33a9fb5-7f02-4b21-a691-c9a4faf3d5fa.png)

**Comment by neilsf** [comment]
XC=BASIC uses the 24-bit overlapped version of this algorithm: https://github.com/bbbradsmith/prng_6502 (Check out the galois24o routine). I think it was designed to be fast rather than unpredictable :-)
In a future version I might add several algorithms, so that the programmer may choose one, e. g. `RNDL(<method>)`.

**Comment by orlof** [comment]
Hmm, I ran some tests with Galois and it did not repeat like this. It seems like rndl is not generating 24 random bits, but shifting seed bits 15:4 to a new positions (23:12) and then generating only 12 new random bits. I understand if this is a design choice (i.e. speed optimisation) but in that case another option would be to have slower rndl that generates 24 random bits and faster rndb that generates only 8 random bits.

**Comment by orlof** [comment]
I just realized that I may have misunderstood the rndl. Does it actually call Galois only once and then return 
the whole seed register instead of calling Galois 3 times and constructing the long from the generated random bytes?

**Comment by orlof** [comment]
Yes :) I was able to reconstruct the sequence and that is exactly how it works. So the actual random number is only the 8 bits in the least significant byte of the returned long. Without knowing the use case for this, I would prefer having rndb (and perhaps also rndi and rndl, but constructed from consecutive calls to Galois instead of returning the seed register).

**Comment by neilsf** [comment]
> I just realized that I may have misunderstood the rndl. Does it actually call Galois only once and then return the whole seed register instead of calling Galois 3 times and constructing the long from the generated random bytes?

Yes it only calls Galois once and I think it's a mistake. I will fix the function to call Galois 3 times and use the consecutive low bytes to form a new 24-bit number.

**Comment by neilsf** [comment]
Okay so I've created a new build. The RNDL() fn should now work as discussed above. Since this adds quite a big overhead, I've added the RNDB(), RNDI() and RNDW() functions that only generate 1, 2 and 2 random bytes, respectively (yet undocumented).

**Comment by orlof** [comment]
Super! Now all sequences look correct.
![image](https://user-images.githubusercontent.com/1869202/149729071-95e59fc1-f4a2-4e54-83ac-d22235ed4d42.png)
