### ISSUE TITLE
fp arithmetics are failing

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#58]
```
DIM f AS FLOAT
f = 1.0 + 0.1
print f

f = 1.0 - 0.1
print f

f = 1.0 * 0.1
print f

f = 1.0 / 0.1
print f
```
First three provide wrong values and division hangs c64.
![image](https://user-images.githubusercontent.com/1869202/149748133-9f9ebfb5-0d9b-40c0-b08c-f4efe024bd9b.png)

**Comment by neilsf** [comment]
Thanks! The optimizer again messes up something :-) If you compile with `--optimize=false`, it works.
