### ISSUE TITLE
Accept constants where a literal number is accepted

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#63]
I am not sure if this is intended, but fyi

```
CONST PORT_1 = $DC01
CONST PORT_2 = $DC00

_PORTS:
DATA AS WORD 0, PORT_1, PORT_2
```

**Comment by neilsf** [comment]
Only numbers are accepted yet. Can be improved later.

**Comment by orlof** [comment]
It would be useful to allow expressions of constants and literal values in e.g. DATA values and DIM dimensions.

**Comment by johanberntsson** [comment]
Just want to add my support to allowing constants in DIM statements, and also when declaring arguments. For example
Const MAX_STRING = 80
sub test(s as String * MAX_STRING)
end sub

**Comment by neilsf** [comment]
Scheduled in version 3.1. Constants should be accepted everywhere where a literal number is accepted.

**Comment by fredrikr** [comment]
Will it also be possible to use expressions where numbers or constants are expected, like:

Constant A = 5;
Constant A_PLUS_1 = A + 1;
