### ISSUE TITLE
FOR NEXT's STEP -1 is not always working.

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#69]
REM -- works!!!!!
FOR X AS BYTE = 1 to 5
	print "1 to 5: " + str$(x)
NEXT

REM -- fails!!!!! 
FOR X AS BYTE = 10 TO 5 STEP -1
	print "step -1: " + str$(x)
NEXT

**Comment by neilsf** [comment]
Not a bug.
All values in a FOR <value> TO <value> STEP <value> construct must be of the same type. In your case, this type is BYTE. Since -1 is an INT, it is converted to BYTE as 255.
