### ISSUE TITLE
ASM keyword does not inject any code

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#74]
At least I could not get the example in docs to work (change the background color).

**Comment by neilsf** [comment]
Regression. The comments starting with single quote are now discarded by the parser.
Need to rethink the syntax of ASM ... END ASM blocks. Writing assembly code as comments doesn't work any more :-(

**Comment by orlof** [comment]
Without knowing anything about the technical challenges, I suppose that the easiest syntax from user perspective would be just:
```
ASM
    lda #$00
    sta $d021
END ASM
```
Maybe you could implement new parser token that handles everything inside ASM similar to literal string... or something :-)

**Comment by neilsf** [comment]
This is also what I originally wanted.
However the BIG technical challenge (at least for my limited understanding in grammar parsing :-P) is to make the grammar parser ignore everything between ASM and END ASM keywords and not try to understand those lines as BASIC code.
I'll give it another try.

**Comment by neilsf** [comment]
Fixed. No need to escape assembly code any more. Everything inside the ASM ... END ASM block is now copied to the assembly code.
