### ISSUE TITLE
Concat'ing a string to another string fails if the first string is blank

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#75]
Hopefully I did not do something stupid this time.  ;)

![image](https://user-images.githubusercontent.com/14124210/150643659-d2fd0e70-84ce-4df2-af94-dadab5906c56.png)

![image](https://user-images.githubusercontent.com/14124210/150643702-07b3e166-30f5-433f-9484-5c2027d6f414.png)

**Comment by neilsf** [comment]
No, that's definitely a bug :-) Fixed now, it'll get into the next build soon.
