### ISSUE TITLE
Reverse on/off PETSCII not working

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#77]
![image](https://user-images.githubusercontent.com/14124210/150671235-ea67f4b2-e1a4-4f78-816f-d5768f6f3f3c.png)

**Comment by jakebullet70** [comment]
Just noticed, seems like the PETSCII codes are for V2, not version 3.

**Comment by neilsf** [comment]
They should work in v3, too.

**Comment by jakebullet70** [comment]
OK, we have a bug then.
