### ISSUE TITLE
Add ability to prefix imported items from INCLUDE statement

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#79]
There is always a possibility that using a module will import objects that conflict (naming) with other imported modules. It would be nice to have the ability to add a prefix to the things imported by the module:

```
INCLUDE "mod1.bas" NAMED "mine"
INCLUDE "mod2.bas" NAMED "theirs"

PRINT mine.ToString(22)
PRINT theirs.ToString(22)
```

**Comment by neilsf** [comment]
It's a cool feature but I'm not sure it can be implemented in this major version of XC=BASIC. I'm closing this now, but keep it in mind.
