### ISSUE TITLE
SHARED does not work with variables

### ISSUE THREAD

**Issue by dtomas** [neilsf/xc-basic3#94]
Variables cannot be accessed outside of their module, despite being defined as `SHARED`.

Example:

module.bas:
```basic
DIM var AS INT SHARED
LET var = 1234
```

main.bas:
```basic
INCLUDE "module.bas"

PRINT var
```

ERROR: Variable "var" does not exist or is unknown in this scope

Also doesn't work for arrays, but `CONST`, `FUNCTION` and `SUB` all work.

**Comment by neilsf** [comment]
Fixed now. Thanks for reporting!
