### ISSUE TITLE
Latest version fails to compile

### ISSUE THREAD

**Issue by jakebullet70** [neilsf/xc-basic3#96]
Downloaded latest version today and my program fails to compile now, if I rollback to previous version it compiles again

![image](https://user-images.githubusercontent.com/14124210/152326279-d0037778-4e91-4b91-8074-14ab875e8494.png)
[DS.zip](https://github.com/neilsf/xc-basic3/files/7993742/DS.zip)

**Comment by neilsf** [comment]
Fixed now. Thanks.
