### ISSUE TITLE
Allow comments in type definitions etc.

### ISSUE THREAD

**Issue by johanberntsson** [neilsf/xc-basic3#98]
Currently it is not allowed to add comments in type declarations, which makes the code harder to read. It would be good if something like this would work
type Gamestate
   ' the game state is used when saving a level to disk
    screenbase as word: ' address to the level map
   enemyseed as word: '  controls enemy spawning
end type
Basically it would be good if it was possible to add comments everywhere where it makes sense.

**Comment by neilsf** [comment]
It is allowed to add comments, but the comment style has changed. The apostrophe (`'`) character is no longer an alias of REM and therefore the colon (`:`) is not valid between a statement and a comment. Try without the colon and it'll work.
